name: PR build

on: [push, pull_request]

jobs:
  ubuntu-build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.22.1'

      - name: Set up JDK 11.0.7
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.7
      - name: Build with Gradle
        env:
          packageUser: ${{ github.actor }}
          packagePAT: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew build -x :docerina-ui:npmTestDocerinaUI

      - name: Generate Codecov Report
        if:  github.event_name == 'pull_request'
        uses: codecov/codecov-action@v1
        with:
          directory: ./docerina-ui/coverage/

  windows-build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.22.1'
      - name: Set up JDK 11.0.7
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.7
      - name: Build with Gradle
        env:
          packageUser: ${{ github.actor }}
          packagePAT: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew.bat build -x :docerina-ui:npmTestDocerinaUI
